from . import cooker_hood
from . import duct
from . import extractor
from . import sale_order
from . import crm_lead
from . import crm_stage
from . import res_partner
from . import product_template
from . import cyc