{
    'name': 'RELIEX Reports',
    'version': '17.0.0.1',
    'summary': 'Reliex reports',
    'description': 'Reliex reports',
    'category': 'ONMI developments',
    'author': 'ONMI Engineering',
    'license': 'LGPL-3',
    'depends': ['onmi_reliex_contacts', 'onmi_reliex_operations', 'onmi_reliex_photo_report'],
    'data': [
        'report/external_layout_bold.xml',
        'report/sale_order_templates.xml',
        'report/worksheet_part_templates.xml',
        'report/checklist_templates.xml',
        'report/checklist_fire_templates.xml',
        'report/work_order_clean_templates.xml',
        'report/sale_order_report.xml',
        'report/worksheet_part_report.xml',
        'report/checklist_report.xml',
        'report/checklist_fire_report.xml',
        'report/work_order_clean_report.xml',
        'data/mail_template_data.xml',
        'views/res_company_views.xml',
        'views/sale_order_views.xml',
        'views/worksheet_views.xml',
        'views/work_order_clean.xml',
        'views/account_move_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False
}
